// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvVrztRrfNIn5bzx3nucZE0zxpzoVc_90',
    appId: '1:118237122687:web:c05c6b50c6b743c1cbaf4a',
    messagingSenderId: '118237122687',
    projectId: 'edtech-e5440',
    authDomain: 'edtech-e5440.firebaseapp.com',
    storageBucket: 'edtech-e5440.firebasestorage.app',
    measurementId: 'G-VLTZ8EZT45',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFrqogivitq1W7ey_ckX62-143DBYMqHs',
    appId: '1:118237122687:android:fd70393772724d0acbaf4a',
    messagingSenderId: '118237122687',
    projectId: 'edtech-e5440',
    storageBucket: 'edtech-e5440.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8HJcwkPEie3Mn1Na-79f8PH6giP378XE',
    appId: '1:118237122687:ios:a5ac6b7d467e464dcbaf4a',
    messagingSenderId: '118237122687',
    projectId: 'edtech-e5440',
    storageBucket: 'edtech-e5440.firebasestorage.app',
    iosBundleId: 'com.example.edtech',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8HJcwkPEie3Mn1Na-79f8PH6giP378XE',
    appId: '1:118237122687:ios:a5ac6b7d467e464dcbaf4a',
    messagingSenderId: '118237122687',
    projectId: 'edtech-e5440',
    storageBucket: 'edtech-e5440.firebasestorage.app',
    iosBundleId: 'com.example.edtech',
  );

}